// Generated by scripts/build_data.py — do not hand-edit.
window.INGREDIENTS = [
  {
    "name": "Abecean Longfin",
    "effects": [
      "Weakness to Frost",
      "Fortify Sneak",
      "Weakness to Poison",
      "Fortify Restoration"
    ],
    "weight": 0.5,
    "value": 15,
    "location": "Lakes, rivers, streams, fish barrels",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Ancestor Moth Wing",
    "effects": [
      "Damage Stamina",
      "Fortify Conjuration",
      "Damage Magicka Regen",
      "Fortify Enchanting"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Ancestor Glade",
    "dlc": "Dawnguard",
    "source": "creature"
  },
  {
    "name": "Ash Creep Cluster",
    "effects": [
      "Damage Stamina",
      "Invisibility",
      "Resist Fire",
      "Fortify Destruction"
    ],
    "weight": 0.3,
    "value": 20,
    "location": "Harvested from ash covered areas of Solstheim",
    "dlc": "Dragonborn",
    "source": "plant"
  },
  {
    "name": "Ash Hopper Jelly",
    "effects": [
      "Restore Health",
      "Fortify Light Armor",
      "Resist Shock",
      "Weakness to Frost"
    ],
    "weight": 0.3,
    "value": 20,
    "location": "Ash Hopper Corpses",
    "dlc": "Dragonborn",
    "source": "creature"
  },
  {
    "name": "Ashen Grass Pod",
    "effects": [
      "Resist Fire",
      "Weakness to Shock",
      "Fortify Lockpicking",
      "Fortify Sneak"
    ],
    "weight": 0.1,
    "value": 1,
    "location": "Harvested from ash covered areas of Solstheim",
    "dlc": "Dragonborn",
    "source": "plant"
  },
  {
    "name": "Bear Claws",
    "effects": [
      "Restore Stamina",
      "Fortify Health",
      "Fortify One-Handed",
      "Damage Magicka Regen"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Bears",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Bee",
    "effects": [
      "Restore Stamina",
      "Ravage Stamina",
      "Regenerate Stamina",
      "Weakness to Shock"
    ],
    "weight": 0.1,
    "value": 3,
    "location": "Beehive",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Beehive Husk",
    "effects": [
      "Resist Poison",
      "Fortify Light Armor",
      "Fortify Sneak",
      "Fortify Destruction"
    ],
    "weight": 1.0,
    "value": 5,
    "location": "Beehive",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Berit's Ashes",
    "effects": [
      "Damage Stamina",
      "Resist Fire",
      "Fortify Conjuration",
      "Ravage Stamina"
    ],
    "weight": 0.5,
    "value": 5,
    "location": "Quest item given by Thadgeir",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Bleeding Crown",
    "effects": [
      "Weakness to Fire",
      "Fortify Block",
      "Weakness to Poison",
      "Resist Magic"
    ],
    "weight": 0.3,
    "value": 10,
    "location": "Mushroom clusters",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Blisterwort",
    "effects": [
      "Damage Stamina",
      "Frenzy",
      "Restore Health",
      "Fortify Smithing"
    ],
    "weight": 0.2,
    "value": 12,
    "location": "Caves and dark areas",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Blue Butterfly Wing",
    "effects": [
      "Damage Stamina",
      "Fortify Conjuration",
      "Damage Magicka Regen",
      "Fortify Enchanting"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Blue Butterfly",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Blue Dartwing",
    "effects": [
      "Resist Shock",
      "Fortify Pickpocket",
      "Restore Health",
      "Fear"
    ],
    "weight": 0.1,
    "value": 1,
    "location": "Hovering above water",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Blue Mountain Flower",
    "effects": [
      "Restore Health",
      "Fortify Conjuration",
      "Fortify Health",
      "Damage Magicka Regen"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Mountain flower clumps",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Boar Tusk",
    "effects": [
      "Fortify Stamina",
      "Fortify Health",
      "Fortify Block",
      "Frenzy"
    ],
    "weight": 0.5,
    "value": 20,
    "location": "Tusked Bristlebacks",
    "dlc": "Dragonborn",
    "source": "creature"
  },
  {
    "name": "Bone Meal",
    "effects": [
      "Damage Stamina",
      "Resist Fire",
      "Fortify Conjuration",
      "Ravage Stamina"
    ],
    "weight": 0.5,
    "value": 5,
    "location": "Draugr and skeletons",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Briar Heart",
    "effects": [
      "Restore Magicka",
      "Fortify Block",
      "Paralysis",
      "Fortify Magicka"
    ],
    "weight": 0.5,
    "value": 20,
    "location": "Forsworn Leaders",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Burnt Spriggan Wood",
    "effects": [
      "Weakness to Fire",
      "Fortify Alteration",
      "Damage Magicka Regen",
      "Slow"
    ],
    "weight": 0.5,
    "value": 20,
    "location": "Burnt Spriggans",
    "dlc": "Dragonborn",
    "source": "creature"
  },
  {
    "name": "Butterfly Wing",
    "effects": [
      "Restore Health",
      "Fortify Barter",
      "Lingering Damage Stamina",
      "Damage Magicka"
    ],
    "weight": 0.1,
    "value": 3,
    "location": "Monarch Butterfly",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Canis Root",
    "effects": [
      "Damage Stamina",
      "Fortify One-Handed",
      "Fortify Marksman",
      "Paralysis"
    ],
    "weight": 0.1,
    "value": 5,
    "location": "Near rocky areas",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Charred Skeever Hide",
    "effects": [
      "Restore Stamina",
      "Cure Disease",
      "Resist Poison",
      "Restore Health"
    ],
    "weight": 0.5,
    "value": 1,
    "location": "Found at campfires",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Chaurus Eggs",
    "effects": [
      "Weakness to Poison",
      "Fortify Stamina",
      "Damage Magicka",
      "Invisibility"
    ],
    "weight": 0.2,
    "value": 10,
    "location": "Falmer caves",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Chaurus Hunter Antennae",
    "effects": [
      "Damage Stamina",
      "Fortify Conjuration",
      "Damage Magicka Regen",
      "Fortify Enchanting"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Chaurus Hunter Chaurus Hunter Fledgling",
    "dlc": "Dawnguard",
    "source": "creature"
  },
  {
    "name": "Chicken's Egg",
    "effects": [
      "Resist Magic",
      "Damage Magicka Regen",
      "Waterbreathing",
      "Lingering Damage Stamina"
    ],
    "weight": 0.5,
    "value": 2,
    "location": "Chicken's Nest",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Creep Cluster",
    "effects": [
      "Restore Magicka",
      "Damage Stamina Regen",
      "Fortify Carry Weight",
      "Weakness to Magic"
    ],
    "weight": 0.2,
    "value": 1,
    "location": "Hydro-thermal areas",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Crimson Nirnroot",
    "effects": [
      "Damage Health",
      "Damage Stamina",
      "Invisibility",
      "Resist Magic"
    ],
    "weight": 0.2,
    "value": 10,
    "location": "Blackreach",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Cyrodilic Spadetail",
    "effects": [
      "Damage Stamina",
      "Fortify Restoration",
      "Fear",
      "Ravage Health"
    ],
    "weight": 0.3,
    "value": 15,
    "location": "Lakes, rivers, streams, fish barrels",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Daedra Heart",
    "effects": [
      "Restore Health",
      "Damage Stamina Regen",
      "Damage Magicka",
      "Fear"
    ],
    "weight": 0.5,
    "value": 250,
    "location": "Daedra",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Deathbell",
    "effects": [
      "Damage Health",
      "Ravage Stamina",
      "Slow",
      "Weakness to Poison"
    ],
    "weight": 0.1,
    "value": 4,
    "location": "Wild, on planters",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Dragon's Tongue",
    "effects": [
      "Resist Fire",
      "Fortify Barter",
      "Fortify Illusion",
      "Fortify Two-handed"
    ],
    "weight": 0.1,
    "value": 5,
    "location": "Hydro-thermal areas",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Dwarven Oil",
    "effects": [
      "Weakness to Magic",
      "Fortify Illusion",
      "Regenerate Magicka",
      "Restore Magicka"
    ],
    "weight": 0.3,
    "value": 15,
    "location": "Dwemer Ruins",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Ectoplasm",
    "effects": [
      "Restore Magicka",
      "Fortify Destruction",
      "Fortify Magicka",
      "Damage Health"
    ],
    "weight": 0.1,
    "value": 25,
    "location": "Ghostlike creatures",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Elves Ear",
    "effects": [
      "Restore Magicka",
      "Fortify Marksman",
      "Weakness to Frost",
      "Resist Fire"
    ],
    "weight": 0.1,
    "value": 10,
    "location": "Plant, hanging herbs",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Emperor Parasol Moss",
    "effects": [
      "Damage Health",
      "Fortify Magicka",
      "Regenerate Health",
      "Fortify Two-Handed"
    ],
    "weight": 0.3,
    "value": 1,
    "location": "Hanging from Emperor Parasol around Tel Mithryn.",
    "dlc": "Dragonborn",
    "source": "plant"
  },
  {
    "name": "Eye of Sabre Cat",
    "effects": [
      "Restore Stamina",
      "Ravage Health",
      "Damage Magicka",
      "Restore Health"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Sabre Cat,Snowy Sabre Cat",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Falmer Ear",
    "effects": [
      "Damage Health",
      "Frenzy",
      "Resist Poison",
      "Fortify Lockpicking"
    ],
    "weight": 0.2,
    "value": 10,
    "location": "Falmer",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Felsaad Tern Feathers",
    "effects": [
      "Restore Health",
      "Fortify Light Armor",
      "Cure Disease",
      "Resist Magic"
    ],
    "weight": 0.1,
    "value": 15,
    "location": "Felsaad Tern",
    "dlc": "Dragonborn",
    "source": "creature"
  },
  {
    "name": "Fire Salts",
    "effects": [
      "Weakness to Frost",
      "Resist Fire",
      "Restore Magicka",
      "Regenerate Magicka"
    ],
    "weight": 0.3,
    "value": 50,
    "location": "Flame Atronach",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Fly Amanita",
    "effects": [
      "Resist Fire",
      "Fortify Two-handed",
      "Frenzy",
      "Regenerate Stamina"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Mushroom clusters in and around caves",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Frost Mirriam",
    "effects": [
      "Resist Frost",
      "Fortify Sneak",
      "Ravage Magicka",
      "Damage Stamina Regen"
    ],
    "weight": 0.1,
    "value": 1,
    "location": "Hanging in homes, businesses and giant camps",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Frost Salts",
    "effects": [
      "Weakness to Fire",
      "Resist Frost",
      "Restore Magicka",
      "Fortify Conjuration"
    ],
    "weight": 0.3,
    "value": 100,
    "location": "Frost Atronach",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Garlic",
    "effects": [
      "Resist Poison",
      "Fortify Stamina",
      "Regenerate Magicka",
      "Regenerate Health"
    ],
    "weight": 0.3,
    "value": 1,
    "location": "Hanging in homes, businesses and cooking areas",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Giant Lichen",
    "effects": [
      "Weakness to Shock",
      "Ravage Health",
      "Weakness to Poison",
      "Restore Magicka"
    ],
    "weight": 0.3,
    "value": 5,
    "location": "Swamps",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Giant's Toe",
    "effects": [
      "Damage Stamina",
      "Fortify Health",
      "Fortify Carry Weight",
      "Damage Stamina Regen"
    ],
    "weight": 1.0,
    "value": 20,
    "location": "Giants",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Gleamblossom",
    "effects": [
      "Resist Magic",
      "Fear",
      "Regenerate Health",
      "Paralysis"
    ],
    "weight": 0.1,
    "value": 5,
    "location": "Harvested in Darkfall Cave, Forgotten Vale",
    "dlc": "Dawnguard",
    "source": "plant"
  },
  {
    "name": "Glow Dust",
    "effects": [
      "Damage Magicka",
      "Damage Magicka Regen",
      "Fortify Destruction",
      "Resist Shock"
    ],
    "weight": 0.5,
    "value": 20,
    "location": "Wispmother",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Glowing Mushroom",
    "effects": [
      "Resist Shock",
      "Fortify Destruction",
      "Fortify Smithing",
      "Fortify Health"
    ],
    "weight": 0.2,
    "value": 5,
    "location": "Caves, Dwemer Ruins",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Grass Pod",
    "effects": [
      "Resist Poison",
      "Ravage Magicka",
      "Fortify Alteration",
      "Restore Magicka"
    ],
    "weight": 0.1,
    "value": 1,
    "location": "Tundras",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Hagraven Claw",
    "effects": [
      "Resist Magic",
      "Lingering Damage Magicka",
      "Fortify Enchanting",
      "Fortify Barter"
    ],
    "weight": 0.3,
    "value": 20,
    "location": "Hagraven",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Hagraven Feathers",
    "effects": [
      "Damage Magicka",
      "Fortify Conjuration",
      "Frenzy",
      "Weakness to Shock"
    ],
    "weight": 0.1,
    "value": 20,
    "location": "Hagraven",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Hanging Moss",
    "effects": [
      "Damage Magicka",
      "Fortify Health",
      "Damage Magicka Regen",
      "Fortify One-Handed"
    ],
    "weight": 0.3,
    "value": 1,
    "location": "Vegetated areas, hanging in caves, from buildings",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Hawk Beak",
    "effects": [
      "Restore Stamina",
      "Resist Frost",
      "Fortify Carry Weight",
      "Resist Shock"
    ],
    "weight": 0.3,
    "value": 15,
    "location": "Hawks",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Hawk Feathers",
    "effects": [
      "Cure Disease",
      "Fortify Light Armor",
      "Fortify One-Handed",
      "Fortify Sneak"
    ],
    "weight": 0.1,
    "value": 15,
    "location": "Hawks",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Hawk's Egg",
    "effects": [
      "Resist Magic",
      "Damage Magicka Regen",
      "Waterbreathing",
      "Lingering Damage Stamina"
    ],
    "weight": 0.5,
    "value": 2,
    "location": "Hawk's Nest",
    "dlc": "Hearthfire",
    "source": "creature"
  },
  {
    "name": "Histcarp",
    "effects": [
      "Restore Stamina",
      "Fortify Magicka",
      "Damage Stamina Regen",
      "Waterbreathing"
    ],
    "weight": 0.3,
    "value": 6,
    "location": "Lakes, rivers, streams and fish barrels",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Honeycomb",
    "effects": [
      "Restore Stamina",
      "Fortify Block",
      "Fortify Light Armor",
      "Ravage Stamina"
    ],
    "weight": 1.0,
    "value": 5,
    "location": "Beehive",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Human Flesh",
    "effects": [
      "Damage Health",
      "Paralysis",
      "Restore Magicka",
      "Fortify Sneak"
    ],
    "weight": 0.3,
    "value": 1,
    "location": "Falmer Vampire dens",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Human Heart",
    "effects": [
      "Damage Health",
      "Damage Magicka",
      "Damage Magicka Regen",
      "Frenzy"
    ],
    "weight": 1.0,
    "value": 0,
    "location": "Falmer Vampire dens",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Ice Wraith Teeth",
    "effects": [
      "Weakness to Frost",
      "Fortify Heavy Armor",
      "Invisibility",
      "Weakness to Fire"
    ],
    "weight": 0.3,
    "value": 30,
    "location": "Ice Wraith",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Imp Stool",
    "effects": [
      "Damage Health",
      "Lingering Damage Health",
      "Paralysis",
      "Restore Health"
    ],
    "weight": 0.3,
    "value": 0,
    "location": "Mushroom clusters near caves or dungeons",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Jarrin Root",
    "effects": [
      "Damage Health",
      "Damage Magicka",
      "Damage Stamina",
      "Damage Magicka Regen"
    ],
    "weight": 0.5,
    "value": 10,
    "location": "Dark Brotherhood Quest",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Jazbay Grapes",
    "effects": [
      "Weakness to Magic",
      "Fortify Magicka",
      "Regenerate Magicka",
      "Ravage Health"
    ],
    "weight": 0.2,
    "value": 1,
    "location": "Hydro-thermal regions",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Juniper Berries",
    "effects": [
      "Weakness to Fire",
      "Fortify Marksman",
      "Regenerate Health",
      "Damage Stamina Regen"
    ],
    "weight": 0.1,
    "value": 1,
    "location": "Juniper Trees",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Large Antlers",
    "effects": [
      "Restore Stamina",
      "Fortify Stamina",
      "Slow",
      "Damage Stamina Regen"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Deer, Elk",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Lavender",
    "effects": [
      "Resist Magic",
      "Fortify Stamina",
      "Ravage Magicka",
      "Fortify Conjuration"
    ],
    "weight": 0.1,
    "value": 1,
    "location": "Outdoors in clumps",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Luna Moth Wing",
    "effects": [
      "Damage Magicka",
      "Fortify Light Armor",
      "Regenerate Health",
      "Invisibility"
    ],
    "weight": 0.1,
    "value": 5,
    "location": "Luna Moth",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Moon Sugar",
    "effects": [
      "Weakness to Fire",
      "Resist Frost",
      "Restore Magicka",
      "Regenerate Magicka"
    ],
    "weight": 0.3,
    "value": 50,
    "location": "Khajiit Caravans",
    "dlc": "Base",
    "source": "purchased"
  },
  {
    "name": "Mora Tapinella",
    "effects": [
      "Restore Magicka",
      "Lingering Damage Health",
      "Regenerate Stamina",
      "Fortify Illusion"
    ],
    "weight": 0.3,
    "value": 4,
    "location": "Dead Trees",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Mudcrab Chitin",
    "effects": [
      "Restore Stamina",
      "Cure Disease",
      "Resist Poison",
      "Resist Fire"
    ],
    "weight": 0.3,
    "value": 2,
    "location": "Mudcrabs",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Namira's Rot",
    "effects": [
      "Damage Magicka",
      "Fortify Lockpicking",
      "Fear",
      "Regenerate Health"
    ],
    "weight": 0.3,
    "value": 0,
    "location": "Caves",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Netch Jelly",
    "effects": [
      "Paralysis",
      "Fortify Carry Weight",
      "Restore Stamina",
      "Fear"
    ],
    "weight": 0.5,
    "value": 20,
    "location": "Netch",
    "dlc": "Dragonborn",
    "source": "creature"
  },
  {
    "name": "Nightshade",
    "effects": [
      "Damage Health",
      "Damage Magicka Regen",
      "Lingering Damage Stamina",
      "Fortify Destruction"
    ],
    "weight": 0.1,
    "value": 8,
    "location": "Graveyards, undead areas",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Nirnroot",
    "effects": [
      "Damage Health",
      "Damage Stamina",
      "Invisibility",
      "Resist Magic"
    ],
    "weight": 0.2,
    "value": 10,
    "location": "Near water",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Nordic Barnacle",
    "effects": [
      "Damage Magicka",
      "Waterbreathing",
      "Regenerate Health",
      "Fortify Pickpocket"
    ],
    "weight": 0.2,
    "value": 5,
    "location": "Underwater",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Orange Dartwing",
    "effects": [
      "Restore Stamina",
      "Ravage Magicka",
      "Fortify Pickpocket",
      "Lingering Damage Health"
    ],
    "weight": 0.1,
    "value": 1,
    "location": "Hovering above water",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Pearl",
    "effects": [
      "Restore Stamina",
      "Fortify Block",
      "Restore Magicka",
      "Resist Shock"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Satchels, Alchemy Laboratory of a Homestead† Pearl Oyster‡",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Pine Thrush Egg",
    "effects": [
      "Restore Stamina",
      "Fortify Lockpicking",
      "Weakness to Poison",
      "Resist Shock"
    ],
    "weight": 0.5,
    "value": 2,
    "location": "Nests in forests",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Poison Bloom",
    "effects": [
      "Damage Health",
      "Slow",
      "Fortify Carry Weight",
      "Fear"
    ],
    "weight": 0.3,
    "value": 5,
    "location": "Darkfall Cave",
    "dlc": "Dawnguard",
    "source": "plant"
  },
  {
    "name": "Powdered Mammoth Tusk",
    "effects": [
      "Restore Stamina",
      "Fortify Sneak",
      "Weakness to Fire",
      "Fear"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Giant Camps, Alchemy Laboratory of a Homestead†",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Purple Mountain Flower",
    "effects": [
      "Restore Stamina",
      "Fortify Sneak",
      "Lingering Damage Magicka",
      "Resist Frost"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Mountain flower clumps",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Red Mountain Flower",
    "effects": [
      "Restore Magicka",
      "Ravage Magicka",
      "Fortify Magicka",
      "Damage Health"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Mountain flower clumps",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "River Betty",
    "effects": [
      "Damage Health",
      "Fortify Alteration",
      "Slow",
      "Fortify Carry Weight"
    ],
    "weight": 0.3,
    "value": 15,
    "location": "Lakes, rivers, streams and fish barrels",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Rock Warbler Egg",
    "effects": [
      "Restore Health",
      "Fortify One-Handed",
      "Damage Stamina",
      "Weakness to Magic"
    ],
    "weight": 0.5,
    "value": 2,
    "location": "Rock Warbler Nest",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Sabre Cat Tooth",
    "effects": [
      "Restore Stamina",
      "Fortify Heavy Armor",
      "Fortify Smithing",
      "Weakness to Poison"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Sabre Cat,Frost Sabre Cat",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Salmon Roe",
    "effects": [
      "Restore Stamina",
      "Waterbreathing",
      "Fortify Magicka",
      "Regenerate Magicka"
    ],
    "weight": 0.2,
    "value": 5,
    "location": "Salmon jumping up falls, Kitchen of a Homestead†",
    "dlc": "Hearthfire",
    "source": "creature"
  },
  {
    "name": "Salt Pile",
    "effects": [
      "Weakness to Magic",
      "Fortify Restoration",
      "Slow",
      "Regenerate Magicka"
    ],
    "weight": 0.2,
    "value": 2,
    "location": "Merchants, containers, near cooking places",
    "dlc": "Base",
    "source": "purchased"
  },
  {
    "name": "Scaly Pholiota",
    "effects": [
      "Weakness to Magic",
      "Fortify Illusion",
      "Regenerate Stamina",
      "Fortify Carry Weight"
    ],
    "weight": 0.3,
    "value": 4,
    "location": "Dead birch trees",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Scathecraw",
    "effects": [
      "Ravage Health",
      "Ravage Stamina",
      "Ravage Magicka",
      "Lingering Damage Health"
    ],
    "weight": 0.1,
    "value": 1,
    "location": "Harvested all over Solstheim",
    "dlc": "Dragonborn",
    "source": "plant"
  },
  {
    "name": "Silverside Perch",
    "effects": [
      "Restore Stamina",
      "Damage Stamina Regen",
      "Ravage Health",
      "Resist Frost"
    ],
    "weight": 0.3,
    "value": 15,
    "location": "Lakes, rivers, streams and fish barrels",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Skeever Tail",
    "effects": [
      "Damage Stamina Regen",
      "Ravage Health",
      "Damage Health",
      "Fortify Light Armor"
    ],
    "weight": 0.2,
    "value": 3,
    "location": "Skeever",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Slaughterfish Egg",
    "effects": [
      "Resist Poison",
      "Fortify Pickpocket",
      "Lingering Damage Health",
      "Fortify Stamina"
    ],
    "weight": 0.2,
    "value": 3,
    "location": "Underwater",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Slaughterfish Scales",
    "effects": [
      "Resist Frost",
      "Lingering Damage Health",
      "Fortify Heavy Armor",
      "Fortify Block"
    ],
    "weight": 0.1,
    "value": 3,
    "location": "Slaughterfish",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Small Antlers",
    "effects": [
      "Weakness to Poison",
      "Fortify Restoration",
      "Lingering Damage Stamina",
      "Damage Health"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Elk",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Small Pearl",
    "effects": [
      "Restore Stamina",
      "Fortify One-Handed",
      "Fortify Restoration",
      "Resist Frost"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Pearl Oyster‡",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Snowberries",
    "effects": [
      "Resist Fire",
      "Fortify Enchanting",
      "Resist Frost",
      "Resist Shock"
    ],
    "weight": 0.1,
    "value": 4,
    "location": "Snowberry bush, snowy areas",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Spawn Ash",
    "effects": [
      "Ravage Stamina",
      "Resist Fire",
      "Fortify Enchanting",
      "Ravage Magicka"
    ],
    "weight": 0.1,
    "value": 20,
    "location": "Ash Spawn",
    "dlc": "Dragonborn",
    "source": "creature"
  },
  {
    "name": "Spider Egg",
    "effects": [
      "Damage Stamina",
      "Damage Magicka Regen",
      "Fortify Lockpicking",
      "Fortify Marksman"
    ],
    "weight": 0.2,
    "value": 5,
    "location": "Spider lairs",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Spriggan Sap",
    "effects": [
      "Damage Magicka Regen",
      "Fortify Enchanting",
      "Fortify Smithing",
      "Fortify Alteration"
    ],
    "weight": 0.2,
    "value": 15,
    "location": "Spriggan",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Swamp Fungal Pod",
    "effects": [
      "Resist Shock",
      "Lingering Damage Magicka",
      "Paralysis",
      "Restore Health"
    ],
    "weight": 0.3,
    "value": 5,
    "location": "Swamps",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Taproot",
    "effects": [
      "Weakness to Magic",
      "Fortify Illusion",
      "Regenerate Magicka",
      "Restore Magicka"
    ],
    "weight": 0.5,
    "value": 15,
    "location": "Spriggan",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Thistle Branch",
    "effects": [
      "Resist Frost",
      "Ravage Stamina",
      "Resist Poison",
      "Fortify Heavy Armor"
    ],
    "weight": 0.1,
    "value": 1,
    "location": "Thistle Plant",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Torchbug Thorax",
    "effects": [
      "Restore Stamina",
      "Lingering Damage Magicka",
      "Weakness to Magic",
      "Fortify Stamina"
    ],
    "weight": 0.1,
    "value": 1,
    "location": "Torchbugs, glowing at night",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Trama Root",
    "effects": [
      "Weakness to Shock",
      "Fortify Carry Weight",
      "Damage Magicka",
      "Slow"
    ],
    "weight": 0.2,
    "value": 1,
    "location": "Harvested from ashen areas of Solstheim",
    "dlc": "Dragonborn",
    "source": "plant"
  },
  {
    "name": "Troll Fat",
    "effects": [
      "Resist Poison",
      "Fortify Two-handed",
      "Frenzy",
      "Damage Health"
    ],
    "weight": 1.0,
    "value": 15,
    "location": "Trolls",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Tundra Cotton",
    "effects": [
      "Resist Magic",
      "Fortify Magicka",
      "Fortify Block",
      "Fortify Barter"
    ],
    "weight": 0.1,
    "value": 1,
    "location": "High mountains below snow line, tundra",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Vampire Dust",
    "effects": [
      "Invisibility",
      "Restore Magicka",
      "Regenerate Health",
      "Cure Disease"
    ],
    "weight": 0.2,
    "value": 25,
    "location": "Vampires, the Silver Hand",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Void Salts",
    "effects": [
      "Weakness to Shock",
      "Resist Magic",
      "Damage Health",
      "Fortify Magicka"
    ],
    "weight": 0.2,
    "value": 125,
    "location": "Storm Atronach",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Wheat",
    "effects": [
      "Restore Health",
      "Fortify Health",
      "Damage Stamina Regen",
      "Lingering Damage Magicka"
    ],
    "weight": 0.1,
    "value": 5,
    "location": "Grows on farms, containers",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "White Cap",
    "effects": [
      "Weakness to Frost",
      "Fortify Heavy Armor",
      "Restore Magicka",
      "Ravage Magicka"
    ],
    "weight": 0.3,
    "value": 0,
    "location": "Mushroom clusters near caves or dungeons",
    "dlc": "Base",
    "source": "plant"
  },
  {
    "name": "Wisp Wrappings",
    "effects": [
      "Restore Stamina",
      "Fortify Destruction",
      "Fortify Carry Weight",
      "Resist Magic"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Wispmother",
    "dlc": "Base",
    "source": "creature"
  },
  {
    "name": "Yellow Mountain Flower",
    "effects": [
      "Resist Poison",
      "Fortify Restoration",
      "Fortify Health",
      "Damage Stamina Regen"
    ],
    "weight": 0.1,
    "value": 2,
    "location": "Darkfall Cave",
    "dlc": "Dawnguard",
    "source": "plant"
  }
];
